apiVersion: apps/v1
kind: Deployment
metadata:
  name: go02-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go02
  template:
    metadata:
      labels:
        app: go02
    spec:
      containers:
        - name: go02
          image: asia-docker.pkg.dev/tops-410414/go02/go02:7d659b3e6849641be36af74729bdee0e8ea7df7f
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: go02-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: go02-secret
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: go02-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: go02-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: go02-secret
                  key: DB_PASSWORD
