name: Deploy

on:
  push:
    branches:
      - main

env:
  ARTIFACT_HOST: asia-docker.pkg.dev
  ARTIFACT_REPO: go02
  SERVICE_NAME: go02

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure docker for artifact registry
        run: |
          gcloud auth configure-docker ${{ env.ARTIFACT_HOST }}

      - name: Build and push Docker image
        env:
          IMAGE: ${{ env.ARTIFACT_HOST }}/${{ secrets.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        run: |
          docker build -t $IMAGE .
          docker push $IMAGE
