name: Deploy

on:
  push:
    branches:
      - main

env:
  DOCKER_HOST: asia-docker.pkg.dev
  SERVICE_NAME: go02

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GCP Artifact Registry
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure docker for artifact registry
        run: |
          gcloud auth configure-docker ${{ env.DOCKER_HOST }}

      - name: Build and push Docker image
        env:
          IMAGE: ${{ env.DOCKER_HOST }}/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}${{ github.sha }}
        run: |
          docker build -t $IMAGE .
          docker push $IMAGE
